name: "Release"
on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        description: "Optional: Specify a release tag to use instead of the latest"
        default: ''
        required: false
      loglevel:
        type: string
        description: "Optional: Specify the log level"
        default: 'INFO'
        required: false
      devhub_alias:
        type: string
        description: "Specify the devhub alias"
        default: 'devhub'
        required: true
      target_org_alias:
        type: string
        description: "Specify the target org alias"
        default: ''
        required: true
      releaseNamePrefix:
        type: string
        description: "Specify the release name prefix"
        default: 'sf'
        required: true
runs:
  using: "composite"
  steps:
    - name: Determine release tag
      id: release
      run: |
        if [ -z "${INPUT_RELEASE_TAG}" ]; then
          latest_tag=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${GH_AUTH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${REPO}/releases/latest \
          | jq -r '.tag_name')
          
          echo "Latest release tag: $latest_tag"
        else
          latest_tag=${INPUT_RELEASE_TAG}
        fi

        if [ -z "$latest_tag" ]; then
          echo "::error::No latest release found for repository ${REPO}"
          exit 1
        fi

        latest_tag=$(echo "$latest_tag" | tr -d '\n')

        if [[ ! "$latest_tag" =~ ^$RELEASE_NAME_PREFIX_[0-9]{13,14}$ ]]; then
          echo "::error::Invalid release name format: $latest_tag. Expected format: $RELEASE_NAME_PREFIX_<timestamp>"
          exit 1
        fi

        echo "releaseTag="$latest_tag" >> $GITHUB_OUTPUT
      shell: bash
      env:
        INPUT_RELEASE_TAG: ${{ inputs.release_tag  }}
        GH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        RELEASE_NAME_PREFIX: ${{ inputs.releaseNamePrefix }}

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ steps.release.outputs.releaseTag }}
        persist-credentials: false

    - name: Get release asset URL
      id: asset
      run: |
        asset_url=$(curl -s \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${GH_AUTH_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${REPO}/releases/tags/${RELEASE_TAG} \
        | jq -r '.assets[] 
        | select(.name | test("sf-platform_.*\\.yml")) 
        | .browser_download_url')

        if [ -z "$asset_url" ]; then
          echo "::error::No asset matching 'sf-platform_.*\\.yml' found for release ${RELEASE_TAG}"
          exit 1
        fi
        echo "url=$asset_url" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        RELEASE_TAG: "${{ steps.release.outputs.releaseTag }}"

    - name: Download release asset
      run: |
        curl -L -o release_file.yml \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${GH_AUTH_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${ASSET_URL}

        echo "File contents:"
        cat release_file.yml
      shell: bash
      env:
        GH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSET_URL: "${{ steps.asset.outputs.url }}"
        RELEASE_TAG: "${{ steps.release.outputs.releaseTag }}"

    - name: Release to Org
      run: |
        sfp release --releasedefinition release_file.yml \
          --targetorg ${TARGET_ORG_ALIAS} \
          --devhubalias ${DEVHUB_ALIAS} \
          --npm \
          --scope ${SCOPE} \
          --loglevel ${SFP_LOG_LEVEL}
      shell: bash
      env:
        SFP_LOG_LEVEL: ${{ inputs.loglevel }}
        SCOPE: ${{ github.repository_owner }}
        TARGET_ORG_ALIAS: ${{ inputs.target_org_alias }}
        DEVHUB_ALIAS: ${{ inputs.devhub_alias }}
        GH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
